services:
  app:
    build: .
    network_mode: host
    depends_on:
      - mongodb
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./assets:/app/assets
      - ./data:/app/data
      - ./assets/fonts/ttf:/usr/share/fonts/ttf
      - /etc/ssl/certs:/etc/ssl/certs:ro
    restart: always
    mem_limit: 4g

  mongodb:
    # 不支持AVX的MongoDB版本
    # image: mongo:4.4.29-ubuntu2004
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data:
