version: '3.8'

services:
  app:
    build: .
    ports:
      - "8008:8008"
    depends_on:
      - mongodb
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./assets:/app/assets
      - ./data:/app/data

  mongodb:
    # 不支持AVX的MongoDB版本
    # image: mongo:4.4.29-ubuntu2004
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data: